package com.cw.vlainter.domain.student.dto

import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.Size
import jakarta.validation.Valid
import com.cw.vlainter.domain.student.entity.StudentCourseMaterialSourceType
import com.cw.vlainter.domain.student.entity.StudentExamSessionStatus
import com.cw.vlainter.domain.student.entity.StudentCourseYoutubeSummaryJobStatus
import com.cw.vlainter.domain.userFile.entity.FileType
import java.time.OffsetDateTime

data class CreateStudentCourseRequest(
    @field:NotBlank(message = "과목명을 입력해 주세요.")
    @field:Size(max = 160, message = "과목명은 160자 이하여야 합니다.")
    val courseName: String,

    @field:Size(max = 120, message = "교수명은 120자 이하여야 합니다.")
    val professorName: String? = null,

    @field:Size(max = 3000, message = "과목 설명은 3000자 이하여야 합니다.")
    val description: String? = null
)

data class CreateStudentCourseYoutubeMaterialRequest(
    @field:NotBlank(message = "유튜브 링크를 입력해 주세요.")
    @field:Size(max = 500, message = "유튜브 링크는 500자 이하여야 합니다.")
    val youtubeUrl: String,

    val format: StudentCourseSummaryDocumentFormat = StudentCourseSummaryDocumentFormat.DOCX
)

data class StudentCourseResponse(
    val courseId: Long,
    val universityName: String,
    val departmentName: String,
    val courseName: String,
    val professorName: String?,
    val description: String?,
    val materialCount: Int = 0,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime
)

data class StudentCourseMaterialResponse(
    val materialId: Long,
    val fileId: Long,
    val fileType: FileType,
    val materialKind: StudentCourseMaterialKind,
    val sourceType: StudentCourseMaterialSourceType,
    val fileName: String,
    val originalFileName: String?,
    val fileUrl: String,
    val createdAt: OffsetDateTime,
    val ingestionStatus: String? = null,
    val ingested: Boolean = false,
    val errorMessage: String? = null,
    val extractionMethod: String? = null,
    val ocrUsed: Boolean = false,
    val visualAssets: List<StudentCourseMaterialVisualAssetResponse> = emptyList()
)

data class StudentCourseYoutubeSummaryJobResponse(
    val jobId: Long,
    val youtubeUrl: String,
    val videoId: String?,
    val videoTitle: String?,
    val summaryTitle: String?,
    val format: StudentCourseSummaryDocumentFormat,
    val transcriptLanguage: String?,
    val autoGeneratedCaption: Boolean,
    val status: StudentCourseYoutubeSummaryJobStatus,
    val errorMessage: String?,
    val generatedMaterialId: Long?,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
    val startedAt: OffsetDateTime?,
    val finishedAt: OffsetDateTime?
)

data class StudentCourseMaterialVisualAssetResponse(
    val assetId: Long,
    val assetType: StudentCourseMaterialVisualAssetType,
    val assetOrder: Int,
    val label: String,
    val pageNo: Int? = null,
    val slideNo: Int? = null,
    val width: Int? = null,
    val height: Int? = null,
    val downloadUrl: String
)

enum class StudentCourseMaterialKind {
    LECTURE_MATERIAL,
    PAST_EXAM
}

enum class StudentCourseMaterialVisualAssetType {
    PDF_PAGE_RENDER,
    PPT_SLIDE_RENDER,
    DOCX_EMBEDDED_IMAGE,
    ORIGINAL_IMAGE
}

data class StudentCourseMaterialDownloadResponse(
    val downloadUrl: String,
    val expiresInSeconds: Long
)

data class CreateStudentCourseSummaryDocumentRequest(
    @field:Size(min = 1, max = 12, message = "요약할 강의자료를 1개 이상 12개 이하로 선택해 주세요.")
    val selectedMaterialIds: List<Long>,

    val format: StudentCourseSummaryDocumentFormat = StudentCourseSummaryDocumentFormat.DOCX
)

data class CreateStudentCourseSummaryPreviewRequest(
    @field:Size(min = 1, max = 12, message = "요약할 강의자료를 1개 이상 12개 이하로 선택해 주세요.")
    val selectedMaterialIds: List<Long>
)

enum class StudentCourseSummaryDocumentFormat {
    DOCX,
    PDF
}

data class StudentCourseSummaryPreviewResponse(
    val title: String,
    val overview: String,
    val coreTakeaways: List<String>,
    val sourceFileNames: List<String>,
    val majorTopics: List<StudentCourseSummaryPreviewTopic>
)

data class StudentCourseSummaryPreviewTopic(
    val title: String,
    val summary: String,
    val subtopics: List<StudentCourseSummaryPreviewSubtopic>
)

data class StudentCourseSummaryPreviewSubtopic(
    val title: String,
    val summary: String,
    val keyPoints: List<String>,
    val supplementaryNotes: List<String>
)

data class CreateStudentExamSessionRequest(
    @field:Min(value = 3, message = "문항 수는 3개 이상이어야 합니다.")
    @field:Max(value = 20, message = "문항 수는 20개 이하여야 합니다.")
    val questionCount: Int = 5,

    val generationMode: StudentExamGenerationMode = StudentExamGenerationMode.STANDARD,

    @field:Min(value = 1, message = "난이도는 1 이상이어야 합니다.")
    @field:Max(value = 5, message = "난이도는 5 이하여야 합니다.")
    val difficultyLevel: Int? = null,

    @field:Size(max = 5, message = "문제 스타일은 최대 5개까지 선택할 수 있습니다.")
    val questionStyles: List<StudentExamQuestionStyle> = emptyList(),

    @field:Size(max = 20, message = "선택 가능한 족보는 최대 20개입니다.")
    val selectedPastExamMaterialIds: List<Long> = emptyList()
)

enum class StudentExamGenerationMode {
    STANDARD,
    FAST_REVIEW,
    PAST_EXAM,
    PAST_EXAM_PRACTICE,
    WRONG_ANSWER_RETEST
}

enum class StudentExamQuestionStyle {
    DEFINITION,
    CODING,
    CALCULATION,
    ESSAY,
    PRACTICAL
}

data class StudentExamSessionResponse(
    val sessionId: Long,
    val courseId: Long,
    val title: String,
    val status: StudentExamSessionStatus,
    val generationMode: StudentExamGenerationMode,
    val difficultyLevel: Int?,
    val questionStyles: List<StudentExamQuestionStyle>,
    val questionCount: Int,
    val maxScore: Int,
    val sourceMaterialCount: Int,
    val answeredCount: Int,
    val totalScore: Int?,
    val submittedAt: OffsetDateTime?,
    val previewQuestions: List<String>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime
)

data class StudentExamQuestionResponse(
    val questionId: Long,
    val questionOrder: Int,
    val questionStyle: StudentExamQuestionStyle,
    val questionText: String,
    val canonicalAnswer: String,
    val gradingCriteria: String,
    val referenceExample: String?,
    val maxScore: Int,
    val answerText: String?,
    val score: Int?,
    val feedback: String?,
    val isCorrect: Boolean?,
    val answeredAt: OffsetDateTime?,
    val sourceFileName: String? = null,
    val sourceVisualAssets: List<StudentCourseMaterialVisualAssetResponse> = emptyList()
)

data class StudentExamSessionDetailResponse(
    val sessionId: Long,
    val courseId: Long,
    val title: String,
    val status: StudentExamSessionStatus,
    val generationMode: StudentExamGenerationMode,
    val difficultyLevel: Int?,
    val questionStyles: List<StudentExamQuestionStyle>,
    val questionCount: Int,
    val maxScore: Int,
    val sourceMaterialCount: Int,
    val answeredCount: Int,
    val totalScore: Int?,
    val submittedAt: OffsetDateTime?,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
    val questions: List<StudentExamQuestionResponse>
)

data class StudentWrongAnswerSetResponse(
    val setId: Long,
    val sessionId: Long,
    val courseId: Long,
    val title: String,
    val questionCount: Int,
    val retestSessionId: Long?,
    val previewQuestions: List<String>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime
)

data class StudentWrongAnswerSetDetailResponse(
    val setId: Long,
    val sessionId: Long,
    val courseId: Long,
    val title: String,
    val questionCount: Int,
    val retestSessionId: Long?,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
    val items: List<StudentWrongAnswerItemResponse>
)

data class StudentWrongAnswerItemResponse(
    val questionId: Long,
    val questionOrder: Int,
    val questionStyle: StudentExamQuestionStyle,
    val questionText: String,
    val canonicalAnswer: String,
    val gradingCriteria: String,
    val referenceExample: String?,
    val maxScore: Int,
    val answerText: String?,
    val score: Int?,
    val feedback: String?,
    val sourceFileName: String? = null,
    val sourceVisualAssets: List<StudentCourseMaterialVisualAssetResponse> = emptyList()
)

data class SubmitStudentExamAnswersRequest(
    @field:Valid
    val answers: List<StudentExamAnswerRequest>
)

data class CreateStudentWrongAnswerSetRequest(
    @field:Size(max = 200, message = "오답노트 제목은 200자 이하여야 합니다.")
    val title: String? = null,

    @field:Size(min = 1, max = 20, message = "저장할 문제를 1개 이상 선택해 주세요.")
    val questionIds: List<Long>
)

data class StudentExamAnswerRequest(
    val questionId: Long,

    @field:Size(max = 5000, message = "답안은 5000자 이하여야 합니다.")
    val answerText: String
)
