@file:Suppress("JpaDataSourceORMInspection")

package com.cw.vlainter.domain.student.entity

import com.cw.vlainter.domain.student.dto.StudentCourseSummaryDocumentFormat
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.PrePersist
import jakarta.persistence.PreUpdate
import jakarta.persistence.Table
import java.time.OffsetDateTime

@Entity
@Table(name = "student_course_youtube_summary_jobs")
class StudentCourseYoutubeSummaryJob(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0,

    @Column(name = "course_id", nullable = false)
    var courseId: Long,

    @Column(name = "user_id", nullable = false)
    var userId: Long,

    @Column(name = "university_name", nullable = false, length = 120)
    var universityName: String,

    @Column(name = "department_name", nullable = false, length = 120)
    var departmentName: String,

    @Column(name = "course_name", nullable = false, length = 160)
    var courseName: String,

    @Column(name = "professor_name", length = 120)
    var professorName: String? = null,

    @Column(name = "youtube_url", nullable = false, length = 500)
    var youtubeUrl: String,

    @Column(name = "video_id", length = 32)
    var videoId: String? = null,

    @Column(name = "video_title", length = 300)
    var videoTitle: String? = null,

    @Column(name = "summary_title", length = 300)
    var summaryTitle: String? = null,

    @Enumerated(EnumType.STRING)
    @Column(name = "format", nullable = false, length = 16)
    var format: StudentCourseSummaryDocumentFormat = StudentCourseSummaryDocumentFormat.DOCX,

    @Column(name = "transcript_language", length = 32)
    var transcriptLanguage: String? = null,

    @Column(name = "auto_generated_caption", nullable = false)
    var autoGeneratedCaption: Boolean = false,

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 40)
    var status: StudentCourseYoutubeSummaryJobStatus = StudentCourseYoutubeSummaryJobStatus.QUEUED,

    @Column(name = "error_message", columnDefinition = "text")
    var errorMessage: String? = null,

    @Column(name = "summary_json", columnDefinition = "text")
    var summaryJson: String? = null,

    @Column(name = "generated_material_id")
    var generatedMaterialId: Long? = null,

    @Column(name = "created_at", nullable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @Column(name = "updated_at", nullable = false)
    var updatedAt: OffsetDateTime = OffsetDateTime.now(),

    @Column(name = "started_at")
    var startedAt: OffsetDateTime? = null,

    @Column(name = "finished_at")
    var finishedAt: OffsetDateTime? = null
) {
    @PrePersist
    fun prePersist() {
        val now = OffsetDateTime.now()
        createdAt = now
        updatedAt = now
    }

    @PreUpdate
    fun preUpdate() {
        updatedAt = OffsetDateTime.now()
    }
}

enum class StudentCourseYoutubeSummaryJobStatus {
    QUEUED,
    FETCHING_CAPTIONS,
    REFINING_TRANSCRIPT,
    GENERATING_SUMMARY,
    READY,
    FAILED
}
