package com.cw.vlainter.domain.student.service

import io.github.thoroldvix.api.Transcript
import io.github.thoroldvix.api.TranscriptApiFactory
import io.github.thoroldvix.api.TranscriptRetrievalException
import io.github.thoroldvix.api.YoutubeTranscriptApi
import org.slf4j.LoggerFactory
import org.springframework.boot.web.client.RestTemplateBuilder
import org.springframework.http.HttpStatus
import org.springframework.stereotype.Service
import org.springframework.web.client.RestTemplate
import org.springframework.web.server.ResponseStatusException
import java.net.URI
import java.text.Normalizer

@Service
class YouTubeTranscriptService(
    restTemplateBuilder: RestTemplateBuilder
) {
    private val logger = LoggerFactory.getLogger(javaClass)
    private val transcriptApi: YoutubeTranscriptApi = TranscriptApiFactory.createDefault()
    private val restTemplate: RestTemplate = restTemplateBuilder.build()

    fun extractTranscript(youtubeUrl: String): ExtractedYouTubeTranscript {
        val normalizedUrl = youtubeUrl.trim()
        if (normalizedUrl.isBlank()) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "유튜브 링크를 입력해 주세요.")
        }
        val videoId = extractYoutubeVideoId(normalizedUrl)
            ?: throw ResponseStatusException(HttpStatus.BAD_REQUEST, "지원하지 않는 유튜브 링크 형식입니다.")

        val transcript = try {
            selectTranscript(videoId)
        } catch (ex: TranscriptRetrievalException) {
            logger.warn("유튜브 자막 목록 조회 실패 videoId={} reason={}", videoId, ex.message)
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "영상 자막을 가져오지 못했습니다.")
        }

        val transcriptContent = try {
            transcript.fetch()
        } catch (ex: TranscriptRetrievalException) {
            logger.warn("유튜브 자막 본문 조회 실패 videoId={} reason={}", videoId, ex.message)
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "영상 자막을 읽지 못했습니다.")
        }

        val transcriptText = transcriptContent.getContent()
            .mapNotNull { fragment -> fragment.text.trim().takeIf { it.isNotBlank() } }
            .joinToString("\n")
            .let(::normalizeTranscriptText)

        if (transcriptText.isBlank()) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "영상 자막을 읽었지만 분석 가능한 텍스트가 비어 있습니다.")
        }

        return ExtractedYouTubeTranscript(
            videoId = videoId,
            title = fetchVideoTitle(normalizedUrl, videoId),
            transcriptText = transcriptText,
            transcriptLanguage = transcript.languageCode,
            autoGenerated = transcript.isGenerated
        )
    }

    private fun selectTranscript(videoId: String): Transcript {
        val transcriptList = transcriptApi.listTranscripts(videoId)
        return runCatching {
            transcriptList.findManualTranscript("ko", "ko-KR", "en")
        }.getOrElse {
            runCatching {
                transcriptList.findGeneratedTranscript("ko", "ko-KR", "en")
            }.getOrElse { ex ->
                throw ex as? TranscriptRetrievalException
                    ?: TranscriptRetrievalException("영상에서 사용할 자막을 찾지 못했습니다.", ex)
            }
        }
    }

    private fun fetchVideoTitle(youtubeUrl: String, videoId: String): String {
        val watchUrl = "https://www.youtube.com/watch?v=$videoId"
        val body = runCatching {
            restTemplate.getForObject(watchUrl, String::class.java)
                ?: restTemplate.getForObject(youtubeUrl, String::class.java)
                ?: ""
        }.getOrDefault("")

        val title = Regex(""""title":"(.*?)"""")
            .find(body)
            ?.groupValues
            ?.getOrNull(1)
            ?.replace("""\"""", "\"")
            ?.replace("\\u0026", "&")
            ?.trim()
            ?.takeIf { it.isNotBlank() }

        return title ?: "YouTube 강의"
    }

    private fun extractYoutubeVideoId(rawUrl: String): String? {
        val uri = runCatching { URI(rawUrl) }.getOrNull() ?: return null
        val host = uri.host?.lowercase()?.removePrefix("www.") ?: return null
        return when (host) {
            "youtu.be" -> uri.path.trim('/').takeIf { it.isNotBlank() }
            "youtube.com", "m.youtube.com" -> {
                val queryParams = uri.rawQuery.orEmpty()
                    .split('&')
                    .mapNotNull { pair ->
                        val index = pair.indexOf('=')
                        if (index <= 0) null else pair.substring(0, index) to pair.substring(index + 1)
                    }
                    .toMap()
                queryParams["v"]?.takeIf { it.isNotBlank() }
                    ?: when {
                        uri.path.startsWith("/shorts/") -> uri.path.removePrefix("/shorts/").substringBefore('/').takeIf { it.isNotBlank() }
                        uri.path.startsWith("/embed/") -> uri.path.removePrefix("/embed/").substringBefore('/').takeIf { it.isNotBlank() }
                        else -> null
                    }
            }
            else -> null
        }
    }

    private fun normalizeTranscriptText(text: String): String {
        return text.lineSequence()
            .map { line -> Normalizer.normalize(line, Normalizer.Form.NFC).trim() }
            .filter { it.isNotBlank() }
            .joinToString("\n")
    }
}

data class ExtractedYouTubeTranscript(
    val videoId: String,
    val title: String,
    val transcriptText: String,
    val transcriptLanguage: String?,
    val autoGenerated: Boolean
)
