package com.cw.vlainter.domain.student.service

import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import io.github.thoroldvix.api.Transcript
import io.github.thoroldvix.api.TranscriptApiFactory
import io.github.thoroldvix.api.TranscriptRetrievalException
import io.github.thoroldvix.api.YoutubeTranscriptApi
import org.slf4j.LoggerFactory
import org.springframework.boot.web.client.RestTemplateBuilder
import org.springframework.http.HttpEntity
import org.springframework.http.HttpHeaders
import org.springframework.http.HttpMethod
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.stereotype.Service
import org.springframework.web.client.RestTemplate
import org.springframework.web.util.HtmlUtils
import org.springframework.web.server.ResponseStatusException
import java.io.StringReader
import java.net.URI
import java.text.Normalizer
import javax.xml.parsers.DocumentBuilderFactory
import org.xml.sax.InputSource

@Service
class YouTubeTranscriptService(
    restTemplateBuilder: RestTemplateBuilder
) {
    private val logger = LoggerFactory.getLogger(javaClass)
    private val transcriptApi: YoutubeTranscriptApi = TranscriptApiFactory.createDefault()
    private val restTemplate: RestTemplate = restTemplateBuilder.build()
    private val objectMapper = jacksonObjectMapper()

    fun extractTranscript(youtubeUrl: String): ExtractedYouTubeTranscript {
        val normalizedUrl = youtubeUrl.trim()
        if (normalizedUrl.isBlank()) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "유튜브 링크를 입력해 주세요.")
        }
        val videoId = extractYoutubeVideoId(normalizedUrl)
            ?: throw ResponseStatusException(HttpStatus.BAD_REQUEST, "지원하지 않는 유튜브 링크 형식입니다.")

        val transcript = runCatching {
            extractTranscriptViaLibrary(videoId, normalizedUrl)
        }.recoverCatching { ex ->
            logger.warn(
                "유튜브 자막 라이브러리 경로 실패 videoId={} type={} reason={}",
                videoId,
                ex.javaClass.simpleName,
                ex.message
            )
            return@recoverCatching extractTranscriptViaWatchPage(videoId, normalizedUrl)
        }.getOrElse { ex ->
            logger.warn(
                "유튜브 자막 추출 최종 실패 videoId={} type={} reason={}",
                videoId,
                ex.javaClass.simpleName,
                ex.message
            )
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "영상 자막을 가져오지 못했습니다.")
        }

        if (transcript.transcriptText.isBlank()) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "영상 자막을 읽었지만 분석 가능한 텍스트가 비어 있습니다.")
        }
        return transcript
    }

    private fun extractTranscriptViaLibrary(videoId: String, youtubeUrl: String): ExtractedYouTubeTranscript {
        val transcript = selectTranscript(videoId)
        val transcriptContent = transcript.fetch()
        val transcriptText = transcriptContent.getContent()
            .mapNotNull { fragment -> fragment.text.trim().takeIf { it.isNotBlank() } }
            .joinToString("\n")
            .let(::normalizeTranscriptText)

        return ExtractedYouTubeTranscript(
            videoId = videoId,
            title = fetchVideoTitle(youtubeUrl, videoId),
            transcriptText = transcriptText,
            transcriptLanguage = transcript.languageCode,
            autoGenerated = transcript.isGenerated
        )
    }

    private fun extractTranscriptViaWatchPage(videoId: String, youtubeUrl: String): ExtractedYouTubeTranscript {
        val watchPage = fetchWatchPage(videoId, youtubeUrl)
        val playerResponse = runCatching { extractPlayerResponseJson(watchPage, videoId) }
            .recoverCatching { ex ->
                logger.warn("유튜브 watch page 파싱 실패 videoId={} reason={}", videoId, ex.message)
                return@recoverCatching fetchPlayerResponseViaInnerTube(videoId, watchPage)
            }
            .getOrElse { ex ->
                throw ex as? TranscriptRetrievalException
                    ?: TranscriptRetrievalException(videoId, ex.message ?: "플레이어 응답을 읽지 못했습니다.")
            }
        val captionTracks = playerResponse.path("captions")
            .path("playerCaptionsTracklistRenderer")
            .path("captionTracks")
            .takeIf { it.isArray }
            ?: run {
                logger.warn("유튜브 캡션 트랙 누락 videoId={} playabilityStatus={}", videoId, playerResponse.path("playabilityStatus").path("status").asText("UNKNOWN"))
                throw TranscriptRetrievalException(videoId, "영상에서 사용할 자막을 찾지 못했습니다.")
            }
        val selectedTrack = selectCaptionTrack(captionTracks, videoId)
        val captionUrl = selectedTrack.path("baseUrl").asText("").replace("&fmt=srv3", "")
            .takeIf { it.isNotBlank() }
            ?: throw TranscriptRetrievalException(videoId, "자막 다운로드 주소를 찾지 못했습니다.")
        val transcriptXml = fetchText(captionUrl, acceptLanguage = "en-US,en;q=0.9")
        val transcriptText = parseCaptionXml(transcriptXml)
        val title = playerResponse.path("videoDetails").path("title").asText("").trim()
            .ifBlank { "YouTube 강의" }
        return ExtractedYouTubeTranscript(
            videoId = videoId,
            title = title,
            transcriptText = transcriptText,
            transcriptLanguage = selectedTrack.path("languageCode").asText(null),
            autoGenerated = selectedTrack.path("kind").asText("") == "asr"
        )
    }

    private fun fetchWatchPage(videoId: String, youtubeUrl: String): String {
        val canonicalUrl = "https://www.youtube.com/watch?v=$videoId"
        return runCatching {
            fetchText(canonicalUrl, WATCH_PAGE_ACCEPT_LANGUAGE)
        }.recoverCatching {
            fetchText(youtubeUrl, WATCH_PAGE_ACCEPT_LANGUAGE)
        }.getOrElse { ex ->
            throw TranscriptRetrievalException(videoId, "watch page를 가져오지 못했습니다.", ex)
        }
    }

    private fun selectTranscript(videoId: String): Transcript {
        val transcriptList = transcriptApi.listTranscripts(videoId)
        return runCatching {
            transcriptList.findManualTranscript("ko", "ko-KR", "en")
        }.getOrElse {
            runCatching {
                transcriptList.findGeneratedTranscript("ko", "ko-KR", "en")
            }.getOrElse { ex ->
                throw ex as? TranscriptRetrievalException
                    ?: TranscriptRetrievalException("영상에서 사용할 자막을 찾지 못했습니다.", ex)
            }
        }
    }

    private fun extractPlayerResponseJson(watchPage: String, videoId: String): com.fasterxml.jackson.databind.JsonNode {
        val markerIndex = watchPage.indexOf(PLAYER_RESPONSE_MARKER)
        if (markerIndex < 0) {
            throw TranscriptRetrievalException(videoId, "ytInitialPlayerResponse를 찾지 못했습니다.")
        }
        val jsonStart = watchPage.indexOf('{', markerIndex)
        if (jsonStart < 0) {
            throw TranscriptRetrievalException(videoId, "플레이어 응답 JSON 시작 위치를 찾지 못했습니다.")
        }
        val json = extractBalancedJsonObject(watchPage, jsonStart)
            ?: throw TranscriptRetrievalException(videoId, "플레이어 응답 JSON을 파싱하지 못했습니다.")
        return objectMapper.readTree(json)
    }

    private fun extractBalancedJsonObject(source: String, startIndex: Int): String? {
        var depth = 0
        var inString = false
        var escaped = false
        for (index in startIndex until source.length) {
            val char = source[index]
            if (escaped) {
                escaped = false
                continue
            }
            if (char == '\\') {
                escaped = true
                continue
            }
            if (char == '"') {
                inString = !inString
                continue
            }
            if (inString) continue
            if (char == '{') depth += 1
            if (char == '}') {
                depth -= 1
                if (depth == 0) {
                    return source.substring(startIndex, index + 1)
                }
            }
        }
        return null
    }

    private fun fetchPlayerResponseViaInnerTube(
        videoId: String,
        watchPage: String
    ): com.fasterxml.jackson.databind.JsonNode {
        val apiKey = INNER_TUBE_API_KEY_REGEX.find(watchPage)?.groupValues?.getOrNull(1)
            ?: throw TranscriptRetrievalException(videoId, "INNERTUBE_API_KEY를 찾지 못했습니다.")
        val clientVersion = INNER_TUBE_CLIENT_VERSION_REGEX.find(watchPage)?.groupValues?.getOrNull(1)
            ?: throw TranscriptRetrievalException(videoId, "INNERTUBE_CLIENT_VERSION을 찾지 못했습니다.")
        val payload = objectMapper.createObjectNode().apply {
            put("videoId", videoId)
            put("contentCheckOk", true)
            put("racyCheckOk", true)
            set<com.fasterxml.jackson.databind.JsonNode>(
                "context",
                objectMapper.createObjectNode().set<com.fasterxml.jackson.databind.JsonNode>(
                    "client",
                    objectMapper.createObjectNode().apply {
                        put("clientName", "WEB")
                        put("clientVersion", clientVersion)
                        put("hl", "ko")
                        put("gl", "KR")
                    }
                )
            )
        }
        val headers = HttpHeaders().apply {
            contentType = MediaType.APPLICATION_JSON
            set(HttpHeaders.ACCEPT_LANGUAGE, WATCH_PAGE_ACCEPT_LANGUAGE)
            set(HttpHeaders.USER_AGENT, BROWSER_USER_AGENT)
        }
        val response = restTemplate.exchange(
            URI("https://www.youtube.com/youtubei/v1/player?key=$apiKey"),
            HttpMethod.POST,
            HttpEntity(payload.toString(), headers),
            String::class.java
        ).body.orEmpty()
        return objectMapper.readTree(response)
    }

    private fun selectCaptionTrack(
        captionTracks: com.fasterxml.jackson.databind.JsonNode,
        videoId: String
    ): com.fasterxml.jackson.databind.JsonNode {
        val tracks = captionTracks.toList()
        preferredTrack(tracks, generatedOnly = false)?.let { return it }
        preferredTrack(tracks, generatedOnly = true)?.let { return it }
        throw TranscriptRetrievalException(videoId, "영상에서 사용할 자막을 찾지 못했습니다.")
    }

    private fun preferredTrack(
        tracks: List<com.fasterxml.jackson.databind.JsonNode>,
        generatedOnly: Boolean
    ): com.fasterxml.jackson.databind.JsonNode? {
        return PREFERRED_CAPTION_LANGUAGES.asSequence()
            .mapNotNull { preferredLanguage ->
                tracks.firstOrNull { track ->
                    val isGenerated = track.path("kind").asText("") == "asr"
                    if (generatedOnly != isGenerated) return@firstOrNull false
                    val languageCode = track.path("languageCode").asText("").lowercase()
                    languageCode == preferredLanguage || languageCode.startsWith("$preferredLanguage-")
                }
            }
            .firstOrNull()
    }

    private fun parseCaptionXml(xml: String): String {
        val documentBuilderFactory = DocumentBuilderFactory.newInstance().apply {
            setFeature("http://apache.org/xml/features/disallow-doctype-decl", true)
            setFeature("http://xml.org/sax/features/external-general-entities", false)
            setFeature("http://xml.org/sax/features/external-parameter-entities", false)
            isXIncludeAware = false
            isExpandEntityReferences = false
        }
        val builder = documentBuilderFactory.newDocumentBuilder()
        val document = builder.parse(InputSource(StringReader(xml)))
        val nodes = document.getElementsByTagName("text")
        val fragments = mutableListOf<String>()
        for (index in 0 until nodes.length) {
            val text = HtmlUtils.htmlUnescape(nodes.item(index).textContent.orEmpty())
                .trim()
            if (text.isNotBlank()) {
                fragments += text
            }
        }
        return normalizeTranscriptText(fragments.joinToString("\n"))
    }

    private fun fetchText(url: String, acceptLanguage: String): String {
        val headers = HttpHeaders().apply {
            set(HttpHeaders.ACCEPT_LANGUAGE, acceptLanguage)
            set(HttpHeaders.USER_AGENT, BROWSER_USER_AGENT)
        }
        return restTemplate.exchange(
            URI(url),
            HttpMethod.GET,
            HttpEntity<String>(headers),
            String::class.java
        ).body.orEmpty()
    }

    private fun fetchVideoTitle(youtubeUrl: String, videoId: String): String {
        val body = runCatching {
            fetchWatchPage(videoId, youtubeUrl)
        }.getOrDefault("")

        val title = Regex(""""title":"(.*?)"""")
            .find(body)
            ?.groupValues
            ?.getOrNull(1)
            ?.replace("""\"""", "\"")
            ?.replace("\\u0026", "&")
            ?.trim()
            ?.takeIf { it.isNotBlank() }

        return title ?: "YouTube 강의"
    }

    private fun extractYoutubeVideoId(rawUrl: String): String? {
        val uri = runCatching { URI(rawUrl) }.getOrNull() ?: return null
        val host = uri.host?.lowercase()?.removePrefix("www.") ?: return null
        return when (host) {
            "youtu.be" -> uri.path.trim('/').takeIf { it.isNotBlank() }
            "youtube.com", "m.youtube.com" -> {
                val queryParams = uri.rawQuery.orEmpty()
                    .split('&')
                    .mapNotNull { pair ->
                        val index = pair.indexOf('=')
                        if (index <= 0) null else pair.substring(0, index) to pair.substring(index + 1)
                    }
                    .toMap()
                queryParams["v"]?.takeIf { it.isNotBlank() }
                    ?: when {
                        uri.path.startsWith("/shorts/") -> uri.path.removePrefix("/shorts/").substringBefore('/').takeIf { it.isNotBlank() }
                        uri.path.startsWith("/embed/") -> uri.path.removePrefix("/embed/").substringBefore('/').takeIf { it.isNotBlank() }
                        else -> null
                    }
            }
            else -> null
        }
    }

    private fun normalizeTranscriptText(text: String): String {
        return text.lineSequence()
            .map { line -> Normalizer.normalize(line, Normalizer.Form.NFC).trim() }
            .filter { it.isNotBlank() }
            .joinToString("\n")
    }

    companion object {
        private const val PLAYER_RESPONSE_MARKER = "ytInitialPlayerResponse = "
        private const val WATCH_PAGE_ACCEPT_LANGUAGE = "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"
        private const val BROWSER_USER_AGENT =
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
        private val PREFERRED_CAPTION_LANGUAGES = listOf("ko", "en")
        private val INNER_TUBE_API_KEY_REGEX = Regex(""""INNERTUBE_API_KEY":"([^"]+)"""")
        private val INNER_TUBE_CLIENT_VERSION_REGEX = Regex(""""INNERTUBE_CLIENT_VERSION":"([^"]+)"""")
    }
}

data class ExtractedYouTubeTranscript(
    val videoId: String,
    val title: String,
    val transcriptText: String,
    val transcriptLanguage: String?,
    val autoGenerated: Boolean
)
